apiVersion: v1
kind: ConfigMap
metadata:
  name: mywebserver-static
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Video Player</title>
    </head>
    <body>
        <video width="640" height="360" controls>
            <source src="static/unwrapped.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </body>
    </html>

